services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    profiles:
      - dev
    ports:
      - "80:80"


  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
