# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://fareto.dev/"
title: fareto.dev
copyright: "© [Fabricio Arend Torres](https://github.com/FabricioArendTorres/fareto_blog)"
paginate: 5
theme: [hugo-PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]


minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: ""
  author: Fabricio Arend Torres
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "My little Blog on Machine Learning, Scientific Computing and other things."
    Content: |
      **About Me**

      Hi, I'm Fabricio, a Computer Scientist working within Machine Learning and Scientific Computing.
      Welcome to my blog about sharing random tidbits of knowledge within this evergrowing, fast evolving field.

      {{< small >}}(And while there may be many blogs, I will at least not post behind paywalls on Medium ;) ){{< /small >}}


      <br/>   
      **Why start yet another blog on ML and Scientific Computing?**

      If you come from a Computer Science or programming background, you're probably more than used to seeing highly complex topics discussed informally—through blog posts, YouTube videos, and hands-on tutorials. 
      But **that's not a given in every field**.
      
      <br/>       
      Exploring different scientific disciplines deepened my appreciation for this unconventional way of sharing knowledge. 
      Some of the most valuable insights—tiny tricks barely mentioned in papers, undocumented research code quirks, and field-specific "hidden" knowledge—often circulate only within niche communities.
      
      &nbsp;

      Although I'm currently moving away from academia, I still want to contribute to this culture of open knowledge sharing. 
      This blog is my way of doing just that.

      ***

      {{< small >}}
      This website is a static page built using [Hugo](https://gohugo.io/) and [PaperMod template](https://github.com/adityatelange/hugo-PaperMod/), with the source code being openly available on [my GitHub](https://github.com/FabricioArendTorres/fareto_blog).
      Check it out if you're looking to build a simple blog without the hassle of dynamic web pages!
      {{< /small >}}
  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/FabricioArendTorres/fareto_blog"

    - name: linkedin
      title: Connect with me on LinkedIn
      url: "https://www.linkedin.com/in/fabricio-arend-torres/"

  editPost:
    URL: "https://github.com/FabricioArendTorres/fareto_blog/tree/main/app/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
  googleAnalytics:
    id: "${GA4_MEASUREMENT_ID}"  # will be injected/substituted during build time

